---
title: "ESM 204 Assignment 2"
author: "Adrienne Hewitt, Alex Brown"
date: "April 26, 2019"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE, warning=FALSE}

library(tidyverse)
library(knitr)
library(kableExtra)
library(plotly)
library(pwr)
library(car)
library(RColorBrewer)
library(extrafont)
library(ggrepel)
library(effsize)
library(ggpubr)
library(vcdExtra)
library(dplyr)
library(RColorBrewer)
library(corrplot) 
library(janitor) 
library(lubridate) 
library(gganimate)
library(ggimage)
library(stargazer)
```

```{r, include=FALSE, warning=FALSE}

original_data<-read_csv("Hmwk2_Data.csv")

```

###1

```{r, include=FALSE}

low_demand<-lm(Price_Dollars~Q_Low_Gallons_per_Day, data=original_data)

high_demand<-lm(Price_Dollars~Q_High_Gallons_per_Day, data=original_data)

summary(low_demand)

summary(high_demand)

```


```{r}
#defining low demand
lowdemand<-function(x) { 21.9908534 -0.0001355*x}

#defining high demand
highdemand<-function(x) {23.3914418-0.0001297*x}

#defining aggregate demand
aggdemand<-function(x) {22.70647-0.00006626831*x}

#defining supply
supply<-function(x) {0.00001871302*x}

#defining MEC
MEC<-function(x) {2}

```

```{r, echo=FALSE}
demand_plots <- ggplot(original_data, aes(x=Q_Low_Gallons_per_Day, y=Price_Dollars))+
  geom_line()+
  geom_line(color="blue", aes(x=Q_High_Gallons_per_Day)) +
  geom_smooth(method = lm)

demand_plots

demand_curves <- ggplot(data=original_data, aes(x=Q_High_Gallons_per_Day, y=Price_Dollars)) + geom_line(aes(colour=Q_Low_Gallons_per_Day)) + geom_smooth(aes(group=Q_High_Gallons_per_Day))

demand_curves

demand_curve <- ggplot(data.frame(x = c(0, 150000)), aes(x = x)) +
        stat_function(fun = dnorm, args = list(200, 100)) +
        stat_function(fun = dnorm, args = list(700, 50))


demand_curve
```


